version: '3'

networks:
  laravel:
    driver: bridge

services:
  db:
    image: mysql
    platform: linux/amd64
    restart: unless-stopped
    ports:
      - 33060:3306
    volumes:
      - ./dockerData/db/:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gestion
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    networks:
      - laravel

  phpmyadmin:
    image: phpmyadmin
    restart: unless-stopped
    links:
      - db
    ports:
      - 4000:80
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    networks:
      - laravel

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - laravel
